# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2639de8c935b4cbd3e4fa4f7bcc32a6844b2ad4ead96896a469abd9439966a017d516b342880daebdedf3c458df384bb56fd8e96a07cc2d85e696074f0570d92

test:
  secret_key_base: 4a4f6ca39f06103a6f8e14b4b569b3f1959300cca2c37b94e55629d32b744e65b05e07ccc24765807330709596dde31f4a28a7da1ce55ffb516d1a6ef02c9e0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
